### ISSUE TITLE
Indice na tabela {$db_prefix}modulo_cpf

### ISSUE THREAD

**Issue by arvanus** [edersondev/psmodcpf#11]
Olá, eu em geral não uso muito MySQL, mas em geral é interessante termos um índice na coluna documento, não acha?
O índice seria usado no método
`public function checkDuplicate($documento, $id_customer = 0)`
Outra sugestão ainda, é criar `documento` como campo único, evitando que por algum motivo passe nesta verificação...

**Comment by edersondev** [comment]
Olá @arvanus , é uma boa ideia. Em breve irei atualizar o módulo. Obrigado

**Comment by rafael-ribas** [comment]
> Olá, eu em geral não uso muito MySQL, mas em geral é interessante termos um índice na coluna documento, não acha? O índice seria usado no método `public function checkDuplicate($documento, $id_customer = 0)` Outra sugestão ainda, é criar `documento` como campo único, evitando que por algum motivo passe nesta verificação...

Acredito que seria interessante, talvez, verificar se uma possível alteração do nome da tabela "`documento`" para "`cpf_cnpf`", poderia facilitar a compatibilidade entre o módulo do PagSeguro.  

Isso seria interessante, pois ainda não existe nenhuma solução gratuita no marketplace do Prestashop para viabilizar a integração com a PagSeguro, no que diz respeito a inserção do campo "CPF/CNPJ" no cadastro dos clientes.

#12

**Comment by edersondev** [comment]
módulo atualizado, a coluna documento foi setado como único.
