### ISSUE TITLE
Módulo CPF no Amin

### ISSUE THREAD

**Issue by ricardocosta43** [edersondev/psmodcpf#13]
É possível adicionar o módulo do cpf no cadastrodo cliente feito pelo admin?
Eu consegui adicionar os fields mas não entendi porque não salva nem valida se já existe.
Obrigado

**Comment by edersondev** [comment]
Olá Ricardo, que cadastro é esse?

**Comment by ricardocosta43** [comment]
Boa tarde Ederson
no administrativo do prestashop tem o cadastro do cliente
Dai tem vezes que é necessário cadastrar o cliente via painel administrativo e não pelo front
e o módulo que vc desenvolveu não aparece o campo no momento do cadastro, e quando o cadastro vem do front, e não consigo editar o cpf por exemplo

Eu fiz esse ajuste aqui no siste que eu publiquei mas seria interessante para outras pessoas que não são desenvolvedoras que tenham essa opção
Valeu
________________________________
De: Ederson Ferreira ***@***.***>
Enviado: terça-feira, 2 de maio de 2023 11:04
Para: edersondev/psmodcpf ***@***.***>
Cc: ricardocosta43 ***@***.***>; Author ***@***.***>
Assunto: Re: [edersondev/psmodcpf] Módulo CPF no Amin (Issue #13)


Olá Ricardo, que cadastro é esse?

**Comment by edersondev** [comment]
Lancei uma nova versão do módulo que possibilita cadastrar o cpf/cnpj pelo admin. Pode conferir no readme.
https://github.com/edersondev/psmodcpf

**Comment by ricardocosta43** [comment]
Muito Obrigado
Parabéns pelo trabalho
________________________________
De: Ederson Ferreira ***@***.***>
Enviado: quarta-feira, 16 de agosto de 2023 19:44
Para: edersondev/psmodcpf ***@***.***>
Cc: ricardocosta43 ***@***.***>; Author ***@***.***>
Assunto: Re: [edersondev/psmodcpf] Módulo CPF no Amin (Issue #13)


Closed #13<https://github.com/edersondev/psmodcpf/issues/13> as completed.
