### ISSUE TITLE
Prestashop 1.7

### ISSUE THREAD

**Issue by sarment0** [edersondev/psmodcpf#3]
Ola, vc teria o módulo para 1.7?

**Comment by edersondev** [comment]
Por enquanto ainda não tenho para a versão 1.7, mas pretendo fazer em breve.

**Comment by brunoramonalmeida** [comment]
Estamos aguardando!!!

**Comment by edersondev** [comment]
Módulo CPF/CNPJ disponível para a versão 1.7 do prestashop.
