### ISSUE TITLE
Qual seu contato? 

### ISSUE THREAD

**Issue by je4423** [edersondev/psmodcpf#6]
Olá Ederson, boa tarde!
Você está trabalhando com programação ainda? Quais seus contatos? Em qual cidade você está? Estamos procurando parceiros para realizar alguns projetos e também trabalho interno na empresa(fixo). Por favor, envie seus contatos. 
Obrigado,
Jeferson

**Comment by edersondev** [comment]
Estou trabalhando com programação, meu email ederson.dev@gmail.com estou em Brasília.
