### ISSUE TITLE
Adição de Número no endereço

### ISSUE THREAD

**Issue by johnnyvaz** [edersondev/psmodcpf#7]
Olá Ederson
Estou desenvolvendo um módulo para adicionar o campo número no endereço e estou com dificuldade em saber se precisaria de um gancho específico. 
pelo que eu vi não achei um que me ajudasse nesta lista: https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/
eu vi que vc usou o hookActionAdminCustomersFormModifier , e eu precisava de um semelhante a isso mas no address , vc saberia me dizer?

no meu módulo eu faço a busca por cep normalmente, junto com o seu módulo para validar o cfp, ficou bom, só falta o campo número separado.

**Comment by edersondev** [comment]
Olá Johnny,

Os campos do formulário de endereço do PrestaShop são dinâmicos e você pode configura-los no menu International => Localizações na aba Países. Pesquise pelo país desejado e clique em Editar. Para o número do endereço eu utilizo o campo vat_number.

Meu email de contato está no meu perfil, então se tiver mais alguma dúvida pode enviar um email ao invés de abrir uma Issue.
