### ISSUE TITLE
Campo CPF não aparece na administração

### ISSUE THREAD

**Issue by albatroz77** [edersondev/psmodcpf#9]
Olá Ederson!
Antes de mais nada quero agradecer pelo desenvolvimento e disponibilização do código. Obrigado!
Estou com uma loja na versão 1.7.6.5 e instalei o psmodcpf 2.0.5. Os campos foram gerados no banco de dados e os CPF/CNPJ e RG aparecem corretamente como últimos campos na tela de cadastro, inclusive sendo gravados após o cadastro. O problema está na visualização destes dados no painel administrativo, ou seja, quando entro em clientes, os campos não aparecem.
Sabe como posso resolver isso?

**Comment by edersondev** [comment]
Olá Abatroz77, tenho que revisar o ganchos do prestashop para exibir os dados no painel administrativo, em breve farei a correção.

**Comment by albatroz77** [comment]
Opa, legal!
Aguardo ansioso.

**Comment by cganbit** [comment]
Cara parabéns pelo módulo, realmente fantástico, então estou com a mesma dificuldade na visualização destes dados no painel administrativo, ou seja, quando entro em clientes, os campos não aparecem.

De toda forma agradeço mais uma vez pela colaboração

**Comment by edersondev** [comment]
Versão 2.0.6 lançada, corrige a exibição do CPF na tela de editar cliente

**Comment by albatroz77** [comment]
Excelente Ederson!
Muito obrigado por compartilhar. Funcionou perfeitamente no Prestashop 1.7.6.5.
O único detalhe é que tive que renomear a pasta do arquivo zip de "psmodcpf-master" para "psmodcpf", caso contrário dá erro.
Valeu!
